### ISSUE TITLE
Release for Jazzy

### ISSUE THREAD

**Issue by Scout22** [ros2-gbp/ros2_socketcan-release#2]
The upstream package https://github.com/autowarefoundation/ros2_socketcan has updated to be compatible with ros2 jazzy.
Would it be possible to run release the new package using bloom ?

**Comment by Scout22** [comment]
@marcoag

**Comment by marcoag** [comment]
@Scout22 we don't manage that repo nor that release, you might wanna ping the [maintainer](https://github.com/autowarefoundation/ros2_socketcan/blob/3c82371743cd806c7ec038370d247a8728c30a0b/ros2_socketcan/package.xml#L7C1-L7C82) to make the release or offer your help to do it.
